### ISSUE TITLE
limited to 256 character lines

### ISSUE THREAD

**Issue by rocky4546** [pkscout/script.speedfaninfo#3]
My title line for the csv is more than 256 characters which causes an end of line exception.  I made the following change and corrected the issue
    def _parse_line( self, f, s_pos ):
        file_size = f.size()
        read_size = 356
Not sure if 356 is long enough, but it was long enough for me.  I am using your plugin on Ubuntu with a script that creates the log file in the userdata area.  It works great with the line length adjustment.  It gets the APC UPS data, Harddrive temps and the general sensors information. I really like what you have done to make it flexible.

**Comment by pkscout** [comment]
I'm not able to duplicate this using a native Speedfan Log.  I created a header row of 271 characters with no problem.  So I'm thinking maybe there is something in your other script that is creating the file that is causing my script to not properly find the end of the line.  If adjusting the read size works for you, then I'd say just do that.  I'll release another version of SPID that allows to you change the read size in the settings so that you don't have go modify the source code.

**Comment by rocky4546** [comment]
Thanks for the reply.  I rechecked on Ubuntu and the read length does make a difference.  It could be the Linux implementation of Kodi/Python.  I have attached a test file for you in case you are interested in what I created based on SpeedFan format.  I also attached the Bourne shell script used to create it in case you are interested.  You can use it or drop it, that it up to you.  I really like the work you have on this addon and appreciate your work. I have a few suggestions for improvements in case you are interested.  Again, it is upto you.
1) At the top of the __populate_from_all_logs, it would be nice to have an optional call to a script located in the userdata area based on settings.  I have seen this on other addons.  This way, the file can generate based on the addon update rate instead of an external app being called periodically. (I have additional info if you are interested)
2) Add an "other" category in case people want to add sensors that do not follow the voltage, speed, temp categories.  It seems simple and would provide a significant enhancement
Thanks again for the addon and good luck in the fut
[SpeedFanInfoFiles.zip](https://github.com/pkscout/script.speedfaninfo/files/676399/SpeedFanInfoFiles.zip)
ure.

**Comment by pkscout** [comment]
I released a new beta (0.7.5~beta1) that adds options for other sensors (just name them in the log file header as somesensor.other) and to run an external script when checking for log files (look in the advanced settings to enable it and select the script).  There is a default timeout for the external script of 10 seconds.  If the script takes longer than that setting, it will be terminated, at least in theory.  I have no easy way to test the external script stuff, but I do know that it doesn't crash SFID when enabled at least.

**Comment by rocky4546** [comment]
I would love to help test the beta version, but I am not aware how to find it.  I can install from a zip file.  let me know where to get it, please.

**Comment by pkscout** [comment]
The best thing to do is download and install my beta repository from:

https://github.com/pkscout/repository.beta.pkscout/blob/helix/repository.beta.pkscout-1.1.0.zip

Once you do that you can install the beta of SFID by going to the addon area, selecting install from repo, select my repo, and then find the add-on.

**Comment by rocky4546** [comment]
I pulled down your master and checking it out.  Will let you know.

**Comment by rocky4546** [comment]
Looks real good. Only one more change needed.  Line 127 needs to include voltage or other; instead of just voltage.  This is to handle the case where the script adds the scale to the number; such, as "39min".  Everything else worked perfect.  256 size was broken, but setting it to 356 worked, as expected.  The script is called based on the refresh rate, as expected.  "other" field is working for floating point and integers numbers.

**Comment by pkscout** [comment]
OK, that change is in the repo as well as the latest master on GitHub.

**Comment by rocky4546** [comment]
That works.  looks good to me.  Thanks for the updates.
