### ISSUE TITLE
hasSubProcess is not defined

### ISSUE THREAD

**Issue by rocky4546** [pkscout/script.speedfaninfo#5]
Running the external script capability on Ubuntu.  It has worked for a while and now it is erroring.

KODI.LOG
08:49:37.240 T:140152918972160  NOTICE: [SpeedFan Info] script version 0.7.6 started
08:49:37.240 T:140152918972160  NOTICE: [SpeedFan Info] debug logging set to true
08:49:37.241 T:140152918972160 WARNING: CSkinInfo: failed to load skin settings
08:49:37.268 T:140152918972160   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'hasSubProcess' is not defined
                                            Traceback (most recent call last):
                                              File "/home/<user>/.kodi/addons/script.speedfaninfo/default.py", line 56, in onInit
                                                self._populate_from_all_logs()
                                              File "/home/<user>/.kodi/addons/script.speedfaninfo/default.py", line 163, in _populate_from_all_logs
                                                result, loglines = popenWithTimeout( self.EXTERNALSCRIPT, self.EXTERNALTIMEOUT )
                                              File "/home/<user>/.kodi/addons/script.speedfaninfo/resources/common/fileops.py", line 124, in popenWithut
                                                if hasSubProcess:
                                            NameError: global name 'hasSubProcess' is not defined
                                            -->End of Python script error report<--
08:49:43.297 T:140152918972160  NOTICE: [SpeedFan Info] script stopped

SETTING.XML file
<settings>
    <setting id="external_script" value="/home/<user>/kodi/userdata/addon_data/script.speedfaninfo/sensorSpeedFan.sh" /
>
    <setting id="external_timeout" value="10" />
    <setting id="log_location" value="/home/<user>/kodi/userdata/addon_data/script.speedfaninfo/logs/" />
    <setting id="log_location2" value="" />
    <setting id="log_location3" value="" />
    <setting id="log_title" value="" />
    <setting id="log_title2" value="" />
    <setting id="log_title3" value="" />
    <setting id="logging" value="true" />
    <setting id="read_size" value="256" />
    <setting id="show_compact" value="true" />
    <setting id="temp_scale" value="Celcius" />
    <setting id="transparency" value="60" />
    <setting id="update_delay" value="30" />
    <setting id="use_external_script" value="true" />
    <setting id="use_log2" value="false" />
    <setting id="use_log3" value="false" />
</settings>

**Comment by pkscout** [comment]
Sorry about that.  I updated some things to deal with an incompatibility with the Windows Store version of Kodi and thought I had tested everything.  I've fixed it and will submit an update.  In the meantime if you go into:

/home//.kodi/addons/script.speedfaninfo/resources/common/fileops.py

and look for line 124, you can change it to read:

    if hasSubprocess:

(note the lower case 'p').  That should fix it.
